CREATE TABLE IF NOT EXISTS PERMISSIONS
(
    id   UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS GROUPS
(
    id   UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USERS_GROUPS
(
    user_id  UUID REFERENCES USERS (id),
    group_id UUID REFERENCES GROUPS (id),
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS GROUPS_PERMISSIONS
(
    group_id      UUID REFERENCES GROUPS (id),
    permission_id UUID REFERENCES PERMISSIONS (id),
    PRIMARY KEY (group_id, permission_id)
);